### ISSUE TITLE
backward_ros & pal_utils?

### ISSUE THREAD

**Issue by ana-GT** [pal-robotics/dynamic_introspection#1]
Those 2 packages are required (kinetic-devel) but I don't seem to find them.  Could you please point me to where I could download them? Thanks!

**Comment by v-lopez** [comment]
Hi Ana,

Thanks for noticing this, netiher backward_ros or pal_utils were published.

We have now pubilshed backward_ros https://github.com/v-lopez/backward_ros and we are removing the pal_utils dependency.

Later today you'll be able to use this.

Cheers

**Comment by lakshmip001** [comment]
I cloned the backward_ros, but still it requires pal_utils
Can please help for pal_utils?

**Comment by v-lopez** [comment]
We are running internal validation, as soon as we are happy with it we'll publish.

Shouldn't take more than a few hours.

**Comment by v-lopez** [comment]
New version pushed to github. It should solve your issues.

**Comment by lakshmip001** [comment]
I still face some errors with play_motion package.
Errors     << play_motion:make /home/lakshmi/tiago_public_ws/logs/play_motion/build.make.002.log                                                                                                           
In file included from /home/lakshmi/tiago_public_ws/src/play_motion/play_motion/src/approach_planner.cpp:48:0:
/home/lakshmi/new_ws/src/moveit/moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group.h:43:2: warning: #warning "This header is deprecated and will go away in ROS lunar." "Please use moveit/move_group_interface/move_group_interface.h" "and the class MoveGroupInterface instead of MoveGroup" [-Wcpp]
 #warning "This header is deprecated and will go away in ROS lunar."\
  ^
In file included from /home/lakshmi/new_ws/src/moveit/moveit_core/macros/include/moveit/macros/class_forward.h:40:0,
                 from /home/lakshmi/new_ws/src/moveit/moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h:41,
                 from /home/lakshmi/new_ws/src/moveit/moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group.h:40,
                 from /home/lakshmi/tiago_public_ws/src/play_motion/play_motion/src/approach_planner.cpp:48:
/home/lakshmi/new_ws/src/moveit/moveit_core/macros/include/moveit/macros/declare_ptr.h:52:16: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
   typedef std::shared_ptr<Type> Name##Ptr;                                                                             \
                ^
/home/lakshmi/new_ws/src/moveit/moveit_core/macros/include/moveit/macros/class_forward.h:51:3: note: in expansion of macro ‘MOVEIT_DECLARE_PTR’
   MOVEIT_DECLARE_PTR(C, C);
   ^
/home/lakshmi/new_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/link_model.h:50:1: note: in expansion of macro ‘MOVEIT_CLASS_FORWARD’
 MOVEIT_CLASS_FORWARD(Shape);
 ^
/home/lakshmi/new_ws/src/moveit/moveit_core/macros/include/moveit/macros/declare_ptr.h:53:16: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
   typedef std::shared_ptr<const Type> Name##ConstPtr;
                ^
/home/lakshmi/new_ws/src/moveit/moveit_core/macros/include/moveit/macros/class_forward.h:51:3: note: in expansion of macro ‘MOVEIT_DECLARE_PTR’
   MOVEIT_DECLARE_PTR(C, C);
   ^
/home/lakshmi/new_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/link_model.h:50:1: note: in expansion of macro ‘MOVEIT_CLASS_FORWARD’
 MOVEIT_CLASS_FORWARD(Shape);

**Comment by v-lopez** [comment]
Hi, could you please confirm that you are using the kinetic-devel branch from the play_motion repository?

**Comment by lakshmip001** [comment]
Hi, I tried with kinect-devel branch of play_motion . But still i face an error in other package.

Errors     << pal_hardware_gazebo:make /home/lakshmi/tiago_public_ws/logs/pal_hardware_gazebo/build.make.003.log
/home/lakshmi/tiago_public_ws/src/pal_hardware_gazebo/src/pal_hardware_gazebo.cpp: In member function ‘bool gazebo_ros_control::PalHardwareGazebo::parseIMUSensors(ros::NodeHandle&, gazebo::physics::ModelPtr, const urdf::Model*)’:
/home/lakshmi/tiago_public_ws/src/pal_hardware_gazebo/src/pal_hardware_gazebo.cpp:290:17: error: ‘class gazebo::sensors::ImuSensor’ has no member named ‘SetWorldToReferencePose’
     imu_sensor->SetWorldToReferencePose();
                 ^
make[2]: *** [CMakeFiles/pal_hardware_gazebo.dir/src/pal_hardware_gazebo.cpp.o] Error 1
make[1]: *** [CMakeFiles/pal_hardware_gazebo.dir/all] Error 2
make: *** [all] Error 2
cd /home/lakshmi/tiago_public_ws/build/pal_hardware_gazebo; catkin build --get-env pal_hardware_gazebo | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -

**Comment by v-lopez** [comment]
What's your Gazebo version?

The supported gazebo version is 7 for Kinetic, I believe this call has been deprecated after gazebo 7.

**Comment by lakshmip001** [comment]
Gazebo multi-robot simulator, version 7.0.0 Copyright (C) 2012-2016 Open Source Robotics Foundation. Released under the Apache 2 License. http://gazebosim.org

**Comment by v-lopez** [comment]
Please execute:
```dpkg -S ImuSensor.hh```

And paste the output

**Comment by lakshmip001** [comment]
lakshmi@lakshmi-Nitro-AN515-51:~/tiago_public_ws$ dpkg -S ImuSensor.hh
libgazebo7-dev:amd64: /usr/include/gazebo-7/gazebo/sensors/ImuSensor.hh
lakshmi@lakshmi-Nitro-AN515-51:~/tiago_public_ws$ 
lakshmi@lakshmi-Nitro-AN515-51:~/tiago_public_ws$

**Comment by lakshmip001** [comment]
lakshmi@lakshmi-Nitro-AN515-51:~/tiago_public_ws$ dpkg -S ImuSensor.hh
libgazebo7-dev:amd64: /usr/include/gazebo-7/gazebo/sensors/ImuSensor.hh
lakshmi@lakshmi-Nitro-AN515-51:~/tiago_public_ws$ 
lakshmi@lakshmi-Nitro-AN515-51:~/tiago_public_ws$

**Comment by lakshmip001** [comment]
dpkg -S ImuSensor.hh
libgazebo7-dev:amd64: /usr/include/gazebo-7/gazebo/sensors/ImuSensor.hh

**Comment by v-lopez** [comment]
Can you check if the file  /usr/include/gazebo-7/gazebo/sensors/ImuSensor.hh contains the function called `SetWorldToReferencePose`

**Comment by lakshmip001** [comment]
I checked the Imusensor.hh . function SetWorldToReferencePose doesnot exist

**Comment by v-lopez** [comment]
backward_ros has been moved to https://github.com/pal-robotics/backward_ros

We're working on the build issue here https://github.com/pal-robotics/pal_hardware_gazebo/issues/1, it looks like it was added between 7.0.0 (your version) and 7.11.0 (the version we use).

We're trying to make it compatible.

**Comment by joselpart** [comment]
Hi, I am trying to build the Tiago simulation set of packages on Ubuntu 16.04 with ROS Kinetic and I am having issues since the dynamic_introspection package still depends on the pal_utils package which is still not available. In the comments above, it was said that this dependency would be removed, though it is still there. Do you have any updates regarding this? Thanks.

**Comment by v-lopez** [comment]
It's been readded again by mistake by a script that synchronizes our internal repositories with github.

You can use version 1.0.5. We will fix those commits tomorrow morning.
